---
output:
  pdf_document: default
  html_document: default
---
# Exercise 1.4

Linear PDE, rewrite to normal form
\begin{align*}
  \nabla u(x) \begin{bmatrix} -x_2 \\ x_1 \end{bmatrix} - u(x) = 0
\end{align*}
thus
\begin{align*}
  A(x) = \begin{bmatrix} -x_2 \\ x_1 \end{bmatrix}, \quad b(x) = -1, \quad f(x) = 0.
\end{align*}
We then solve $\partial_t\Phi(t,x) = A(\Phi(t,x))$,
\begin{align*}
  \varphi_1'(t) = -\varphi_2(t), \quad \varphi_1(0) = x_1 \\
  \varphi_2'(t) = -\varphi_1(t), \quad \varphi_2(0) = x_2.
\end{align*}
Thus $\Phi(t,x) = e^{t\begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}} = \begin{bmatrix} \cos(t) & -\sin(t) \\ \sin(t) & \cos(t) \end{bmatrix}\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} x_1\cos(t) - x_2\sin(t) \\ x_1\sin(t) + x_2\cos(t) \end{bmatrix}.$
Parameterizing the hypersurface gives $\gamma(q) = \begin{bmatrix} q \\ 0 \end{bmatrix}$.
By Lemma 1.8
\begin{align*}
  X(t,q) = \Phi(t,\gamma(q)) = \begin{bmatrix} q\sin(t) \\ q\cos(t) \end{bmatrix}.
\end{align*}
Inverting the function gives
$$
  x_1 = \cos(t) \ \Leftrightarrow \ \frac{x_1}{q} = \cos(t) \ \Leftrightarrow \ t = \cos^{-1}\left(\frac{x_1}{q}\right).
$$
Now we have found $t$ which we can use to find $q$ as
\begin{align*}
  x_2 &= q\sin(t) \\
  &= q\sin\left(\cos^{-1}\left(\frac{x_1}{q}\right)\right) \\
  &= q\sqrt{1 - \frac{x_1^2}{q^2}} \\
  x_2^2 &= q^2 - x_1^2 \\
  q^2 &= x_1^2 + x_2^2 \\
  q &= \sqrt{x_1^2 + x_2^2} \\
  &= \| x \|.
\end{align*}
By Theorem 1.9
\begin{align*}
  Z(\psi) &= g(\| x \|)e^{-\int_0^{\cos^-1(x_1/\| x \|)}-1 \ \text{d}s} \\
  &= g(\| x \|)e^{\cos^-1(x_1/\| x \|)}.
\end{align*}
Not quite the answer but this is as close as i can get.


# Exercise 1.8
The exercise is to solve the following Cauchy-problem
\begin{align}
  u(x) \partial_1 u(x) + \partial_2 u(x) = 1, 
  \qquad x \in \mathbb{R}^2, 
  \ u(q,q) = 0, \ q \in \mathbb{R} 
\end{align}
with
\begin{align}
  \Sigma = \left\{ (q,q) \ | \ q \in \mathbb{R} \right\}
\end{align}
 
### Transform to normal form
The normal form is given by  
\begin{align}
  u'(x) A(x) + b(x) u(x) = f(x), \qquad x \in \Omega
  (\#eq:normal)
\end{align}
were $u'(x)$ is given by
\begin{align}
  u'(x) = \left[ \partial_1 u(x) \ \ldots \ \partial_d u(x) \right]
\end{align}
We can write our equation as
\begin{align}
  \left[ \partial_1 u(x) \ \partial_2 u(x) \right] 
  \begin{bmatrix}
    u(x) \\
    1
  \end{bmatrix}
  = 1
\end{align}
i.e. our $A(x)$ and $b(x)$ becomes
\begin{align}
  A(x) = \begin{bmatrix} u(x) \\ 1 \end{bmatrix}, \qquad
  b(x) = 1
\end{align}
which in turn gives us that \@ref(eq:normal) becomes
\begin{align}
  \nabla u(x) A(x,z) = 1
\end{align}

### Parameterizing the hypersurface
The initial hypersurface $\Sigma$ by the following
$$\gamma(q) := \begin{bmatrix} q \\ q \end{bmatrix}, \qquad q \in \mathbb{R}.$$
Taking the derivative of the parameterization yields
$$\gamma'(q) = \begin{bmatrix} 1 \\ 1 \end{bmatrix}.$$
The tangent space of $\Sigma$ becomes
$$T_{\gamma(q)}\Sigma = \left\{ \begin{bmatrix} s \\ s \end{bmatrix} \Big| \ s \in \mathbb{R}\right\}.$$
The condition that $A\Big(\gamma(q), \phi(\gamma(q))\Big) \in T_{\gamma(q)}\Sigma$ is always satisfied as $A\Big(\gamma(q), \phi(\gamma(q))\Big)$ is given by the following
$$A\Big(\gamma(q), \phi(\gamma(q))\Big) = \begin{bmatrix} 0 \\ 1\end{bmatrix}.$$
The Cauchy problem is non-characteristic in everything point contained in $\Sigma$.

### System of equations
We get the following system of equations
\begin{align}
  \partial_t x_1(t,q) &= Z(t,q) \quad&&, \ x_1(0,q) = q (\#eq:system1) \\
  \partial_t x_2(t,q) &= 1 \quad&&, \ x_2(0,q) = q (\#eq:system2) \\
  \partial_t Z(t,q) &= 1 \quad&&, \ Z(0,q) = 0 (\#eq:system3)
\end{align}
From \@ref(eq:system3) we quickly see that 
\begin{align} 
  Z(t,q) = t. (\#eq:bigz)
\end{align}
From \@ref(eq:system2) we coclude that
$$x_2(t,q) = q + t.$$
Considering \@ref(eq:system1) and \@ref(eq:bigz) we see that
\begin{align}
  x_1(t,q) &= q + \int_0^t s \ ds \\
  &= q + \frac{1}{2} t^2.
\end{align}

### Finding t and q
We will start by finding $t$, we have the following expressions
$$x_1 = q + \frac{1}{2} t^2, \qquad x_2 = q + t.$$
We can start by isolating $q$ is the second equation
$$q = x_2 - t,$$
inserting this in the first equation gives the following
\begin{align}
  x_1 &= q + \frac{1}{2} t^2 \\
  &= x_2 - t + \frac{1}{2} t^2 (\#eq:x1expression)
\end{align}
Rewriting \@ref(eq:x1expression) gives
\begin{align}
  x_1 - x_2 + \frac{1}{2} = \frac{1}{2}\underbrace{\left(t^2 - 2t + 1\right)}_{(t - 1)^2}(\#eq:texpression)
\end{align}
Multiplying both sides of \@ref(eq:texpression) by $2$ gives
\begin{align}
  (t - 1)^2 &= 2x_1 - 2x_2 + 1 \\
  t - 1 &= \pm\sqrt{2x_1 - 2x_2 + 1} \\
  t &= 1 \pm\sqrt{2x_1 - 2x_2 + 1} (\#eq:psi1)
\end{align}

# Exercise 1.10

Find a solution for the Cauchy-problem
\begin{align*}
  \partial_1u(x) + \partial_2u(x) = u(x)^2 \\
  u(x_1,0) = g(x_1)
\end{align*}

**Solution**:
This is a kvasilinear PDE, we will start by bringing it to normal form
\begin{align*}
  A(x,u(x)) = \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \quad b(x,u(x)) = u(x)^2.
\end{align*}
From Lemma 1.15
\begin{align*}
  \partial_t X_1(t,q) &= 1, \quad &&X_1(0,q) = q \\
  \partial_t X_2(t,q) &= 1, \quad &&X_2(0,q) = 0 \\
  \partial_t Z(t,q) &= Z(t,q)^2, \quad &&Z(0,q) = g(q).
\end{align*}
We solve the system
\begin{align*}
  Z(t,q) &= \frac{1}{\frac{1}{g(q)} - t} \\
  X_1(t,q) &= q + t \\
  X_2(t,q) &= t.
\end{align*}
We can now invert $t$ and $q$
\begin{align*}
  x_1 = q + t, \quad x_2 = t \\
  t = x_2, \quad x_1 = q + x_2 \ \Leftrightarrow \ q = x_1 - x_2.
\end{align*}
From theorem 1.16
\begin{align*}
  u(x) = Z(\psi(x)) = \frac{1}{\frac{1}{g(x_1 - x_2)} - x_2}.
\end{align*}
