---
output:
  html_document: default
  pdf_document: default
---

# Exam Exercises

## Mock exam 1

### Exercise 1
Let 
$$\Omega:=(0,\infty)^2.$$
Calculate the solution to the following Cauchy-Problem,
\begin{align*}
  &x_1\partial_1u(x) + x_2\partial_2u(x) + x_1x_2u(x) = 0, \quad x \in \Omega; \\
  &u(q,q^2) = 5, \quad q > 0.
\end{align*}

**Solution**:
As the exercise does not ask if the problem is non-characteristic, we suppose that it is.
The first step is to bring the problem to normal form.
The normal form is given by 
$$\nabla u(x)A(x) + u(x)b(x) = f(x).$$
In our case 
$$A(x) = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}, \quad b(x) = x_1x_2 \quad \text{and} \quad f(x) = 0.$$

Next we want to parameterize the hypersurface, which becomes $$\gamma(q) := \begin{bmatrix} q \\ q^2 \end{bmatrix}.$$
When then seek 
$$\Phi(t,x),$$ 
which we find as the solution to 
$$\partial\Phi(t,x) = A(\Phi(t,x)).$$
As we in our case have $d = 2$ the ODE can be written as the following system
\begin{align*}
  \varphi_1'(t) &= A(\Phi(t))_1, \quad \varphi_1(0) = x_1 \\
  \varphi_2'(t) &= A(\Phi(t))_2, \quad \varphi_2(0) = x_2,
\end{align*}
by the definiton of $A(x)$ the system becomes
\begin{align*}
  \varphi_1'(t) &= \varphi(t)_1, \quad \varphi_1(0) = x_1 \\
  \varphi_2'(t) &= \varphi(t)_2, \quad \varphi_2(0) = x_2.
\end{align*}
By solving the system we get the following $\Phi(t,x)$ 
$$\Phi(t,x) = \begin{bmatrix} \varphi_1(t,x) \\ \varphi_2(t,x) \end{bmatrix} = \begin{bmatrix} x_1e^t \\ x_2e^t \end{bmatrix}.$$
By Lemma 1.8 we have $X(t,q) = \Phi(t, \gamma(q))$, thus $$X(t,q) = \Phi(t,\gamma(q)) =  \begin{bmatrix} qe^t \\ q^2e^t \end{bmatrix}.$$
As we seek values for $t$ and $q$ we can now invert the functions
\begin{align*}
  x_1 &= qe^t \\
  x_2 &= q^2e^t
\end{align*}
Isolating $q$ in the first equation gives 
$$x_1 = qe^t \Leftrightarrow e^{-t}x_1 = q,$$
Inserting this in the second equation yields
$$x_2 = \left(e^{-t}x_1\right)^2e^t 
= e^{-2t}x_1^2e^t
= e^{-t}x_1^2 
= \frac{1}{e^{t}} x_1^2,$$
this in turn gives
$$x_2 = \frac{1}{e^{t}} x_1^2
\quad \Leftrightarrow \quad
e^t = \frac{x_1^2}{x_2}\\
\quad \Leftrightarrow \quad
\log\left(e^t\right) = \log\left(\frac{x_1^2}{x_2}\right)
\quad \Leftrightarrow \quad
t = \log\left(x_1^2\right) - \log\left(x_2\right).$$
The expression we have now found for $t$ can be inserted into the expression for $x_1$ to get $q$
$$q = x_1 e^{-\left(\log\left(x_1^2\right) - \log\left(x_2\right)\right)}
= x_1 e^{\log\left(x_2\right)-\log\left(x_1^2\right)}
= x_1 \frac{x_2}{x_1^2} = \frac{x_2}{x_1}.$$
To sum up we have now found both $t$ and $q$ as
$$t = \log\left(x_1^2\right) - \log\left(x_2\right), \quad q = \frac{x_2}{x_1}.$$
We can now insert in Theorem 1.9 what we have found.
The theorem states that
$$Z(t,q) = \phi(\gamma(q))e^{-\int_0^tb(X(s,q))ds} + \int_0^t e^{-\int_s^tb(X(r,q))dr}f(X(s,q))ds,$$
with $\phi(\gamma(q))$ being $Z(0,q)$ i.e. the given initial value.
Inserting what we now, especially that $f(x) = 0$, yields
$$Z(\log\left(x_1^2\right) - \log\left(x_2\right),\frac{x_2}{x_1}) = 5 e^{-q^3\int_0^{\log\left(x_1^2\right) - \log\left(x_2\right)} e^{2s}ds} \\
= 5 e^{-q^3 \left[\frac{1}{2}e^{2s}\right]_0^{\log\left(x_1^2\right) - \log\left(x_2\right)}} \\
= 5 e^{-q^3 \frac{1}{2} 
\left(e^{2\left(\log\left(x_1^2\right) - \log\left(x_2\right)\right)} - e^0\right)} \\
= 5 e^{-q^3 \frac{1}{2} \left( e^{2\log\left(\frac{x_1^2}{x_2}\right)} - e^0\right)} \\
= 5 e^{-q^3 \frac{1}{2} \left( e^{\log\left(\frac{x_1^4}{x_2^2}\right)} - e^0\right)} \\
= 5 e^{-q^3 \frac{1}{2} \left( \frac{x_1^4}{x_2^2} - 1\right)} \\
= 5 e^{-\frac{x_2^3}{x_1^3} \frac{1}{2} \left( \frac{x_1^4}{x_2^2} - 1\right)} \\
= 5 e^{-\frac{1}{2} \left( \frac{x_1^4x_2^3}{x_1^3x_2^2} - \frac{x_2^3}{x_1^3}\right)} \\
= 5 e^{-\left(x_1x_2 - x_2^3/x_1^3\right)/2}.$$
Which in turns implies that
$$u(x) = 5 e^{-\left(x_1x_2 - x_2^3/x_1^3\right)/2}, \quad x \in \Omega.$$

### Exercise 2
Let
$$\Omega := \left\{ x \in \mathbb{R}^2 \ \Bigg| \ \ |x_1 - x_2| < \frac{\pi}{2} \right\}$$
Calculate the solution for the Cauchy problem given by
$$\frac{2}{1 + u(x)^2}\partial_1 u(x) + \frac{1}{1 + u(x)^2}\partial_2 u(x) = 1, \quad x \in \Omega \\
u(q,q) = 0, \quad q \in \mathbb{R}.$$

**Solution**
We start by rewriting to normal form
\begin{align*}
  \frac{2}{1 + u(x)^2}\partial_1 u(x) + \frac{1}{1 + u(x)^2}\partial_2 u(x) &= 1 \\
  u'(x)A(x,u(x)) &= b(x,u(x))
\end{align*}
for
\begin{align*}
  u'(x) = \left[ \partial_1 u(x) \ \partial_2 u(x) \right], \quad
  A(x,u(x)) = \begin{bmatrix} \dfrac{2}{1 + u(x)^2} \\ \dfrac{1}{1 + u(x)^2} \end{bmatrix}, \quad
  b(x,u(x)) = 1.
\end{align*}
From Lemma 1.15 we need to solve the following system, notice that the initial condition originate from $u(q,q) = 0$.
\begin{align*}
  \partial_t X_1(t,q) &= A(X(t,q), Z(t,q))_1, \quad &&X_1(0,q) = q \\
  \partial_t X_2(t,q) &= A(X(t,q), Z(t,q))_2, \quad &&X_2(0,q) = q \\
  \partial_t Z(t,q) &= b(X(t,q), Z(t,q)), \quad &&Z(0,q) = 0.
\end{align*}
Inserting what we have found so far yields the following system
\begin{align*}
  \partial_t X_1(t,q) &= \dfrac{2}{1 + Z(t,q)^2}, \quad &&X_1(0,q) = q \\
  \partial_t X_2(t,q) &= \dfrac{1}{1 + Z(t,q)^2}, \quad &&X_2(0,q) = q \\
  \partial_t Z(t,q) &= 1, \quad &&Z(0,q) = 0.
\end{align*}
As $Z(t,q)$ is present in the first to equation, we will start by solving this, then we will insert this in the other two equations and then solve these
\begin{align*}
  Z(t,q) &= t \\
  X_1(t,q) &= 2\tan^{-1}(t) + q \\
  X_2(t,q) &= \tan^{-1}(t) + q.
\end{align*}
We now need to isolate $t$ and $q$ in the to last equations, i.e. 2 equations with 2 unknowns.
$$x_2 = \tan^{-1}(t) + q 
\ \Leftrightarrow \ 
x_2 - q = \tan^{-1}(1)
\ \Leftrightarrow \
\tan(x_2 - q) = t.$$
$$x_1 = 2\tan^{-1}(t) + q
\ \Leftrightarrow \
x_1 = 2(x_2 - q) + q
\ \Leftrightarrow \
x_1 = 2x_2 - q
\ \Leftrightarrow \
q = 2x_2 - x_1.$$
$$t = \tan(x_2 - q) = \tan(x_2 - (2x_2 - x_1)) = \tan(x_1 - x_2).$$
As suggested by Theorem 1.16 we have
$$u(x) = Z(\Psi(x)) = \tan(x_1 - x_2).$$

### Exercise 3
Solve the following initial-value-problem
$$(\partial_t^2 - \partial_x^2)u(t,x) = 0, \quad t,x \in \mathbb{R} \\
u(0,x) = \cos(x), \quad \partial_tu(0,x) = \cos^3(x), \quad x \in \mathbb{R}.$$
*Hint*: $\cos^3(y) = \cos(y) - \sin^2(y)\cos(y)$

**Solution**:
Because we have $d=1$ we can use d'Alemberts formula, recognizing that problem is in fact a wave equation.

Remember that $u(0,x) = g(x)$ and that $\partial_tu(0,x) = h(x)$, i.e.
$$g(x) = \cos(x), \quad h(x) = \cos^3(x).$$
D'Alamberts formula is given by
$$u(t,x) = \frac{1}{2}\left\{g(x + t) - g(x - t)\right\} + \frac{1}{2}\int_{x-t}^{x+t}h(y)\text{d}y.$$
We insert what we know and calculate
$$u(t,x) = \frac{1}{2}\left\{\cos(x + t) - \cos(x - t)\right\} + \frac{1}{2}\int_{x-t}^{x+t}\cos^3(y)\text{d}y \\
= \frac{1}{2}\left\{\cos(x + t) - \cos(x - t)\right\} + \frac{1}{2}\int_{x-t}^{x+t}\cos(y) - \sin^2(y)\cos(y)\text{d}y \\
= \frac{1}{2}\left\{\cos(x + t) - \cos(x - t)\right\} + \frac{1}{2}\int_{x-t}^{x+t}\cos(y)\text{d}y - \frac{1}{2}\int_{x-t}^{x+t}\sin^2(y)\cos(y)\text{d}y \\
= \frac{1}{2}\left\{\cos(x + t) - \cos(x - t)\right\} + \frac{1}{2}[\sin(y)]_{x-t}^{x+t} - \frac{1}{2}\int_{x-t}^{x+t}\sin^2(y)\cos(y)\text{d}y \\
= \frac{1}{2}\left\{\cos(x + t) - \cos(x - t) + \sin(x + t) - \sin(x - t)\right\} - \frac{1}{2}\int_{x-t}^{x+t}\sin^2(y)\cos(y)\text{d}y,$$
what remains is to calculate the last antiderivative, which we will do below using substitution
$$u = \sin(x), \quad \frac{\text{d}u}{\text{d}y} = \cos(y) \ \Leftrightarrow \ \text{d}u = \cos(y)\text{d}y.$$
We can now insert this into the antiderivative remembering that we also need to substitute the bounds, i.e. applying the function $u$ on them
$$\frac{1}{2}\int_{x-t}^{x+t}\sin^2(y)\cos(y)\text{d}y \ \Leftrightarrow \ \frac{1}{2}\int_{x-t}^{x+t}\sin^2(y)\cos(y)\text{d}y \\
\Leftrightarrow \ \frac{1}{2}\int_{\sin(x-t)}^{\sin(x+t)}u^2\text{d}u \ \Leftrightarrow \ \frac{1}{6}[u^3]_{\sin(x-t)}^{\sin(x+t)} \ \Leftrightarrow \ \frac{1}{6}\left(\sin^3(x + t) - \sin^3(x - t)\right).$$
Inserting what we just found, we have expressed the solution explicitly as
$$u(t,x) = \frac{1}{2}\left\{\cos(x + t) - \cos(x - t) + \sin(x + t) - \sin(x - t)\right\} - \frac{1}{6}\left(\sin^3(x + t) - \sin^3(x - t)\right).$$

### Exercise 4
Solve the following intial-value/border-value-problem,
$$\left(\partial_t - \frac{1}{2}\partial_x^2\right)u(t,x) = 0, \quad t>0, \ x \in (0,\pi); \\
u(0,x) = 4 \sin(3x) \cos(3x), \quad x \in (0,\pi); \\
u(t,0) = u(t,\pi) = 0, \quad t>0.$$
*Hint*: $\sin(2y) = 2\sin(y)\cos(y), \ y \in \mathbb{R}.$

**Solution**:
As the problem is on the form of a heat equation with homogenous Dirichlet bound-conditions, the solution according to theorem 4.10 given by
$$u(t,x) = \sum_{n = 1}^\infty e^{-tn^2\pi^2/2\ell^2} B_n \sin(n\pi x/\ell)\text{d}y.$$
We define $B_n$ as
$$B_n := \frac{2}{\ell} \int_0^\ell g(x)\sin(n\pi x/\ell)\text{d}x, \quad n\in\mathbb{N},$$
in our case $\ell = \pi$ and $g(x) = 4\sin(3x)\sin(3x)$, we see that according to the hint
$$\sin(2y) = 2\sin(y)\cos(y) \ \Leftrightarrow \ 2\sin(6y) = 4\sin(3y)\cos(3y).$$
We can see that $g(x) = 2\sin(6x)$, we insert what we know into the definition of $B_n$ to get
$$B_n = \frac{2}{\pi}\int_0^\pi2\sin(6x)\sin(nx)\text{d}x, \quad n \in \mathbb{N}.$$
According to theorem 4.10 the solution to the problem is given by
$$u(t,x) = \sum_{n = 1}^\infty e^{-tn^2/2}\frac{2}{\pi}\int_0^\pi2\sin(6x)\sin(nx)\text{d}x\sin(nx).$$
Furthermore, according to remark C.3 there is only one $n$ for which the term in the sum is not equal to zero, namely $n = 6$, as $n=m$.
Thus the solution can be simplified to the following
$$u(t,x) = 2e^{-t6^2/2}\sin(6x) = 2e^{-18t}\sin(6x).$$

## Mock exam 2

### Exercise 1

Let $\Omega = \left\{ x \in \mathbb{R}^2 \ | \ x_2 > x_1 \right\}$, find the solution to the following Cauchy-problem
\begin{align*}
  &\partial_1u(x) + \partial_2u(x) + x_1u(x) = e^{-x_2^2/2}, \quad x \in \Omega \\
  &u(0,q) = 1, \quad q > 0.
\end{align*}

**Solution**:
The first step is to bring the problem to normal form i.e.
\begin{align*}
  u'(x)A(x) + u(x)b(x) = f(x) \\
  \begin{bmatrix}\partial_1 u(x) & \partial_2 u(x)\end{bmatrix}\begin{bmatrix}1 \\ 1 \end{bmatrix} + u(x)x_1 = e^{-x^2_2/2}
\end{align*}
this implies that
\begin{align*}
  A(x) = \begin{bmatrix}1 \\ 1 \end{bmatrix}, \quad b(x) = x_1, \quad f(x) = e^{-x^2_2/2}
\end{align*}
Parameterizing the hypersurface gives $\gamma(q) = \begin{bmatrix} 0 \\ q \end{bmatrix}$.
We then seek $\Phi(t,x)$ which we find as the solution to $\partial_t\Phi(t,x) = A(\Phi(t,x))$.
As we in our case have $d = 2$, the ODE becomes a system of differential equations given as
\begin{align*}
  \varphi_1'(t) = A(\Phi(t))_1, \quad \varphi_1(0) = x_1 \\
  \varphi_2'(t) = A(\Phi(t))_2, \quad \varphi_2(0) = x_2.
\end{align*}
The system in our case becomes
\begin{align*}
  \varphi_1'(t) = 1, \quad \varphi_1(0) = x_1 \\
  \varphi_2'(t) = 1, \quad \varphi_2(0) = x_2,
\end{align*}
by solving the system we get
$$\Phi(t) = \begin{bmatrix} x_1 + t \\ x_2 + t \end{bmatrix},$$
and by Lemma 1.8 we have
$$X(t,q) = \Phi(t, \gamma(q)) = \begin{bmatrix} t \\ q + t \end{bmatrix}.$$
Thus seeking values for $t$ and $q$ we invert the function
\begin{align*}
  x_1 &= t \\
  x_2 &= q + t.
\end{align*}
This implies that
\begin{align*}
  t &= x_1 \\
  q &= x_2 - X_1.
\end{align*}
We can now insert this into the formula from theorem 1.9
\begin{align*}
  Z(t,q) &= \phi(\gamma(q)) e^{\int_0^tb(X(s,q))\text{d}s} + \int_0^te^{-\int_s^tb(X(r,q))\text{d}r}f(X(s,q))\text{d}s \\
  &= e^{-\int_0^{x_1}s \ \text{d}s} + \int_0^{x_1}e^{-\int_s^{x_1}r \ \text{d}r}e^{-(q + s)^2/2}\text{d}s \\
  &= e^{-\int_0^{x_1}s \ \text{d}s} + \int_0^{x_1}e^{-\int_s^{x_1}r \ \text{d}r}e^{-((x_2 - x_1) + s)^2/2}\text{d}s
\end{align*}
We can start by solving the following integrals
\begin{align*}
  &-\int_0^{x_1}s \ \text{d}s = -\left[ \frac{1}{2}s^2\right]_0^{x_1} = -\frac{1}{2}x^2_1 \\
  &-\int_s^{x_1} r \ \text{d}r = -\left[\frac{1}{2}r^2\right]_s^{x_1} = -\frac{1}{2}\left( x_1^2 - s^2 \right).
\end{align*}
Inserting these gives
\begin{align*}
  Z(t,q) &= e^{-x_1^2/2} + \int_0^{x_1}e^{-\frac{1}{2}\left( x_1^2 - s^2 \right)-((x_2 - x_1)^2 + s^2 + 2(x_2 - x_1)s)/2}\text{d}s \\
  &= e^{-x^2_1/2} + \int_0^{x_1}e^{-\left( x_1^2 - s^2 \right)/2-((x_2 - x_1)^2 + s^2 + 2(x_2 - x_1)s)/2}\text{d}s \\
  &= e^{-x^2_1/2} + \int_0^{x_1}e^{( -x_1^2 + s^2 - (x_2 - x_1)^2 - s^2 - 2(x_2 - x_1)s)/2}\text{d}s \\
  &= e^{-x^2_1/2} + e^{(-x_1^2 - x_2^2 - x_1^2 + 2x_2x_1)/2} \int_0^{x_1}e^{-(x_2 - x_1)s}\text{d}s \\
  &= e^{-x^2_1/2} + e^{-x_1^2 + x_2x_1 - x_2^2/2} \left[-\frac{1}{x_2 - x_1}e^{-(x_2 - x_1)s}\right]_0^{x_1} \\
  &= e^{-x^2_1/2} + e^{-x_1^2 + x_2x_1 - x_2^2/2} \left(-\frac{e^{-(x_2 - x_1)x_1}}{x_2 - x_1} + \frac{1}{x_2 - x_1}\right) \\
  &= e^{-x^2_1/2} + e^{-x_1^2 + x_2x_1 - x_2^2/2} \left(-\frac{e^{-(x_2 - x_1)x_1}}{x_2 - x_1} + \frac{1}{x_2 - x_1}\right) \\
  &= e^{-x^2_1/2} + \frac{e^{-x_1^2 + x_2x_1 - x_2^2/2} - e^{-x_1^2 + x_2x_1 - x_2^2/2 - x_2x_1 + x_1^2}}{x_2 - x_1} \\
  &= e^{-x^2_1/2} + \frac{e^{-x_1^2 + x_2x_1 - x_2^2/2} - e^{ - x_2^2/2}}{x_2 - x_1}.
\end{align*}

### Exercise 2

Let $q_0 > 1$.
Calculate the solution of the following Cauchy-problem in a small neighbourhood of $(1,q_0)$,
\begin{align*}
  x_1\partial_2u(x) - x_2\partial_1u(x) = 0 \\
  u(1,q) = \cos(q), \quad q \in \mathbb{R}.
\end{align*}
*Hint*:
If we use the definition from the notes, then the length of the vector $X(t,q)$ not of $t$.

**Solution**:
This is a linear PDE, so the first thing is to bring it to normal form
\begin{align*}
  \nabla u(x) \begin{bmatrix} -x_2 \\ x_1 \end{bmatrix} + u(x) \cdot 0 = 0,
\end{align*}
thus
\begin{align*}
  A(x) = \begin{bmatrix} -x_2 \\ x_1 \end{bmatrix}, \quad b(x) = 0, \quad f(x) = 0.
\end{align*}
Next we find $\Phi(t,x)$ as $\partial_t\Phi(t,x) = A(\Phi(t,x))$ yields the following system
\begin{align*}
  \varphi_1'(t) &= -\varphi_2(t), \quad &&\varphi_1(0) = x_1 \\
  \varphi_2'(t) &= \varphi_1(t), \quad &&\varphi_2(0) = x_2.
\end{align*}
This is a system of differential equations, which can be expressed in matrix notation as
\begin{align*}
  \begin{bmatrix} \varphi_1'(t) \\ \varphi_2'(t) \end{bmatrix} = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}\begin{bmatrix} \varphi_1(t) \\ \varphi_2(t) \end{bmatrix}.
\end{align*}
By Putzer's algorithm the solution is
\begin{align*}
  \begin{bmatrix} \varphi_1(t) \\ \varphi_2(t) \end{bmatrix} &= e^{t\begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}}\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}\\
  &= \begin{bmatrix} \cos(t) & -\sin(t) \\ \sin(t) & \cos(t) \end{bmatrix}\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}\\
  &=\begin{bmatrix} x_1\cos(t) -x_2\sin(t) \\ x_1\sin(t)  +x_2\cos(t) \end{bmatrix}
\end{align*}
By lemma 1.8
$$X(t,q) = \begin{bmatrix} \cos(t) & -\sin(t) \\ \sin(t) & \cos(t) \end{bmatrix}\begin{bmatrix} 1 \\ q \end{bmatrix}$$
and as the hint suggest the length of the legnth of this vector does not depend on $t$, so
\begin{align*}
  \sqrt{x_1^2 + x_2^2} &= \sqrt{1 + q^2} \\
  x_1^2 + x_2^2 &= 1 + q^2 \\
  q &= \sqrt{x_1^2 + x_2^2 - 1}.
\end{align*}
Thus as $Z(t,q) =  \cos(q)$ and $u(x) = Z(\psi(x))$ it implies that
$$u(x) = \cos\left(\sqrt{x_1^2 + x_2^2 - 1}\right).$$

### Exercise 3
solve the follwoing initial value problem
\begin{align*}
  \left( \partial_t^2 - \partial_x^2 \right)u(t,x) = \sin(x - t), \quad t,x \in \mathbb{R} \\
  u(0,x) = \cos(x), \quad \partial_tu(0,x) = 0, \quad x \in \mathbb{R}.
\end{align*}

**Solution**:
We are dealing with an initial value problem for a wave equation as defined in definition 2.3.
To solve the problem we look to Lemma 2.4.

We need to first solve
\begin{align*}
  \left( \partial_t^2 - \partial_x^2 \right)v(t,x) = 0, \quad t,x \in \mathbb{R} \\
  v(0,x) = \cos(x), \quad \partial_t v(0,x) = 0, \quad x\in \mathbb{R},
\end{align*}
this is done using (2.28), also known as d'Alamberts formula
\begin{align*}
  v(t,x) &= \frac{1}{2} \left\{\cos(x + t) + \cos(x-t)\right\} + \frac{1}{2} \int_{x-t}^{x+t} 0 \ \text{d}y \\
  &= \frac{1}{2} \left\{\cos(x + t) + \cos(x-t)\right\}.
\end{align*}
Then we need to solve
\begin{align*}
   \left( \partial_t^2 - \partial_x^2 \right)w(t,x) = \sin(x - t), \quad t,x \in \mathbb{R} \\
   w(0,x) = \partial_tw(0,x) = 0,
\end{align*}
according to remark 2.26 the solution is given by
\begin{align*}
  w(t,x) 
  &= \frac{1}{2}\left(\int_0^t\int_{x-(t-s)}^{x+t-s}\sin(y - s) \ \text{d}y \ \text{d}s\right) \\
  &= \frac{1}{2}\left(\int_0^t\left[-\cos(s - y)\right]_{x-(t-s)}^{x+t-s} \ \text{d}s\right) \\
  &= \frac{1}{2}\left(\int_0^t \cos(s - x + t - s) - \cos(s - x - t + s) \ \text{d}s\right)
\end{align*}
we split the integral and solve the right most by substitution as follows
$$u = 2s - x - t, \quad \frac{\text{d}u}{\text{d}s} = 2 \ \Leftrightarrow \ \text{d}u = 2 \ \text{d}s \ \Leftrightarrow \ \frac{1}{2} \ \text{d}u = \text{d}s,$$
this gives
\begin{align*}
  &= \frac{1}{2}\left(\int_0^t \cos(x + t) \ \text{d}s - \frac{1}{2}\int_{-x-t}^{t-x} \cos(u) \ \text{d}u\right) \\
  &= \frac{1}{2}\left(\left[\cos(x + t)s\right]_0^t - \frac{1}{2}\left[\sin(u)\right]_{-x-t}^{t-x} \right) \\
  &= \frac{1}{2}\left(\cos(x + t)t - \frac{1}{2}\left(\sin(t-x) - \sin(-x-t)\right) \right) \\
  &= \frac{t}{2}\cos(x + t) - \frac{1}{4}\left(\sin(t-x) - \sin(-x-t)\right) \\
  &= \frac{t}{2}\cos(x + t) + \frac{1}{4}\left(\sin(t - x) - \sin(x + t)\right).
\end{align*}
Now that we have found both solution we to add these to together to achive the solution for the original problem, i.e. $u = v + w$
$$u(t,x) = \frac{1}{2} \left\{\cos(x + t) + \cos(x-t)\right\} + \frac{t}{2}\cos(x + t) + \frac{1}{4}\left(\sin(t - x) - \sin(x + t)\right).$$

### Exercise 4

Solve the following mixed initial-value/boundary-value-problem
\begin{align*}
  \left(\partial_t - \frac{1}{2}\partial_x^2\right)u(t,x) = 0, \quad t > 0, \ x \in (0,\pi) \\
  u(0,x) = \cos^2(7x), \quad x \in (0,\pi) \\
  \partial_xu(t,0) = \partial_xu(t,\pi) = 0, \quad t > 0.
\end{align*}

*Hint*: $\cos^2(y) = (1 + \cos(2y)/2)/2, \quad y \in \mathbb{R}.$

**Solution**: Heat equation on an interval with homogenous Neumann conditions.
we remember the defintion of $A_n$
$$A_n := \frac{2}{\ell}\int_0^\ell g(x)\cos(n\pi x/\ell) \ \text{d}x, \quad n \in \mathbb{N_0}.$$
Theorem 4.11 states that the solution is given by
$$u(t,x) = \frac{A_0}{2} + \sum_{n = 1}^\infty e^{-tn^2\pi^2/2\ell^2}A_n\cos(n\pi x/\ell).$$
In our case $\ell = \pi$ and $g(x) = \cos^2(7x)$, we start by calculating $A_0$
\begin{align*}
  A_0 &= \frac{2}{\pi} \int_0^\pi \cos^2(7x) \ \text{d}x \\
  &= \frac{2}{\pi} \int_0^\pi (1+\cos(14x)/2)/2 \ \text{d}x \\
  &= \frac{2}{\pi}\left( \int_0^\pi \frac{1}{2} \ \text{d}x +\frac{1}{4}\int_0^\pi \cos(14x) \ \text{d}x\right)
\end{align*}
we substitute in the right most integral using
$$u = 14x, \quad \frac{\text{d}u}{\text{d}x} = 14 \ \Leftrightarrow \ \text{d}u = 14 \ \text{d}x \ \Leftrightarrow \ \frac{1}{14} \ \text{d}u = \text{d}x,$$
giving us
\begin{align*}
  &= \frac{2}{\pi}\left( \left[\frac{1}{2}x\right]_0^\pi +\frac{1}{4}\left[\sin(u)\right]_0^{14\pi}\right) \\
  &=\frac{2}{\pi}\frac{\pi}{2} = 1.
\end{align*}
Inserting in the solution
\begin{align*}
  u(t,x) &= \frac{1}{2} + \sum_{n = 1}^{\infty}e^{tn^2/2}\frac{2}{\pi}\left(\int_0^\pi\left(1+\cos(14x)/2\right)/2\cos(nx) \ \text{d}x\right)\cos(nx) \\
  &= \frac{1}{2} + \sum_{n = 1}^{\infty}e^{tn^2/2}\frac{2}{\pi}\left(\int_0^\pi\frac{1}{2} \ \text{d}x \frac{1}{4}\int_0^\pi \cos(14x)\cos(nx) \ \text{d}x\right)\cos(nx) \\
  &= \frac{1}{2} + \sum_{n = 1}^{\infty}e^{tn^2/2}\frac{2}{\pi}\int_0^\pi\frac{1}{2} \ \text{d}x + \frac{1}{2\pi}\int_0^\pi \cos(14x)\cos(nx) \ \text{d}x\cos(nx) \\
  &= \frac{1}{2} + \sum_{n = 1}^{\infty}e^{tn^2/2}\frac{2}{\pi}\int_0^\pi\frac{1}{2} \ \text{d}x + \frac{1}{4\pi}\int_{-\pi}^\pi \cos(14x)\cos(nx) \ \text{d}x\cos(nx) \\
  &= \frac{1}{2} + e^{-t14^2/2} \cos(14x)/4 \\
  &= \frac{1}{2} + \frac{1}{4}e^{-98t} \cos(14x).
\end{align*}
The disappearance of the sum follows form remark C.4 on page 167.